language: node_js
notifications:
  email: false
node_js:
  - '9'
sudo: false
dist: trusty
before_install:
  - npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
install:
  - travis_retry npm install
test:
  - npm test
before_deploy:
  - npm run coverage
deploy:
  - provider: script
    skip_cleanup: true
    script: npx semantic-release
    on:
      branch: master